---
downscale_ratio: 0.125
enable_sound: False
window_visible: False
frame_stack_len: 1
frame_delay: 12
buffer_size: 10000
epochs: 30
phase1_ratio: 0.2
phase2_ratio: 0.9
steps_per_epoch: 2000
learning_rate: 0.001
decay_lr = False
gamma: 0.99
start_epsilon: 1.0
end_epsilon: 0.1
batch_size: 100
model_dir: './checkpoints/take_cover.ckpt'
log_dir: './tensorboard'
num_ckpts: 40
...