---
down_sample_ratio: 0.125
enable_depth_buffer: False
enable_sound: False
frame_delay: 4
buffer_size: 25000
epochs: 2000
phase1_ratio: 0.2
phase2_ratio: 0.9
steps_per_epoch: 2000
learning_rate: 0.0025
gamma: 0
start_epsilon: 1.0
end_epsilon: 0.1
batch_size: 100
model_dir: './checkpoints/take_cover.ckpt'
num_ckpts: 40
...